# Analyzing the SIDER 4.1 data

+ http://sideeffects.embl.de/
+ http://thinklab.com/d/30#4

In [4]:
import csv
import gzip
import collections

In [5]:
import pandas

In [8]:
# Download SIDER data
base_url = 'http://sideeffects.embl.de/media/download/'
filenames = [
    'README',
    'meddra_all_indications.tsv.gz',
    'meddra_all_se.tsv.gz',
    'meddra_freq.tsv.gz',
]
for filename in filenames:
    ! wget --no-verbose --timestamping --directory-prefix download {base_url}/{filename}

! mv download/README download/README.txt

2024-09-04 11:56:48 URL:http://sideeffects.embl.de/media/download//README [3304/3304] -> "download/README" [1]

## STITCH to DrugBank mapping utilities

In [7]:
def stitch_flat_to_pubchem(cid):
    assert cid.startswith('CID')
    return int(cid[3:]) - 1e8

def stitch_stereo_to_pubchem(cid):
    assert cid.startswith('CID')
    return int(cid[3:])

In [9]:
# Read DrugBank terms
url = 'https://raw.githubusercontent.com/dhimmel/drugbank/3e87872db5fca5ac427ce27464ab945c0ceb4ec6/data/drugbank.tsv'
drugbank_df = pandas.read_table(url)[['drugbank_id', 'name']].rename(columns={'name': 'drugbank_name'})

# Pubchem to DrugBank mapping
url = 'https://raw.githubusercontent.com/dhimmel/drugbank/3e87872db5fca5ac427ce27464ab945c0ceb4ec6/data/mapping/pubchem.tsv'
drugbank_map_df = pandas.read_table(url)

In [12]:
url = 'https://raw.githubusercontent.com/iit-Demokritos/drug_id_mapping/main/drug-mappings.tsv'
drugbank_map_df_2 = pandas.read_table(url)

In [13]:
drugbank_map_df_2

,drugbankId,name,ttd_id,pubchem_cid,cas_num,chembl_id,zinc_id,chebi_id,kegg_cid,kegg_id,bindingDB_id,UMLS_cuis,stitch_id
0,DB13088,AZD-0424,D0QG8F,9893171.0,692054-06-1,CHEMBL3545177,NaN,NaN,NaN,NaN,NaN,C4519307,NaN
1,DB13089,Enoxolone,D06EWG,10114.0,471-53-4,CHEMBL230006,ZINC000019203131,30853,C02283,NaN,50233538.0,C0017986,NaN
2,DB13082,Nefiracetam,D0KD5P,71157.0,77191-36-7,CHEMBL260829,ZINC000000003788,135004,NaN,NaN,NaN,C0165264,NaN
3,DB13083,Talarozole,D0AN7B,9799888.0,201410-53-9,CHEMBL459505,NaN,102167,NaN,D09385,50253810.0,C2606129,NaN
4,DB13080,Roluperidone,D0SQ1W,9799284.0,359625-79-9,NaN,NaN,NaN,NaN,NaN,NaN,C4730997,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22344,NaN,N-(2-amino-5-(thiophen-2-yl)phenyl)nicotinamide,D0Q2GM,44454416.0,NaN,CHEMBL256440,ZINC000029127438,NaN,NaN,NaN,50232034.0,NaN,NaN
22345,NaN,2-Cinnamamido-N1-hydroxy-N4-pentylsuccinamide,D0F2HJ,45257111.0,NaN,CHEMBL596560,ZINC000045358109,NaN,NaN,NaN,50304541.0,NaN,NaN
22346,NaN,4-Biphenyl-4-yl-2-cyclohexylmethyl-1H-imidazole,D08KBV,9966703.0,NaN,CHEMBL334104,ZINC000027106397,NaN,NaN,NaN,50223722.0,NaN,NaN
22347,NaN,Naldemedine Tosylate,D0Q2HO,56837137.0,1345728-04-2,CHEMBL3039508,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22348,NaN,H-Dmt-Tic-NH-(R)CH(CH2-COOH)-Bid(N1-Me),D0Q2HZ,25034016.0,NaN,CHEMBL499099,ZINC000049889297,NaN,NaN,NaN,50272228.0,NaN,NaN

In [15]:
drugbank_map_df_2[drugbank_map_df_2['drugbankId'] == 'DB00115']

,drugbankId,name,ttd_id,pubchem_cid,cas_num,chembl_id,zinc_id,chebi_id,kegg_cid,kegg_id,bindingDB_id,UMLS_cuis,stitch_id
2318,DB00115,Cyanocobalamin,D0X4NX,70678590.0,68-19-9,CHEMBL2110563,NaN,17439,C02823,D00166,NaN,C0042845,CID100002891

In [6]:
drugbank_map_df

       drugbank_id  pubchem_id
0          DB00014    11980055
1          DB00014    11981235
2          DB00014    11982741
3          DB00014    16052011
4          DB00014    23581804
...            ...         ...
204704     DB09028    74070157
204705     DB09028    74834862
204706     DB09028    77513518
204707     DB09028    87355970
204708     DB09028    87644641

[204709 rows x 2 columns]

## meddra_freq.tsv.gz

In [7]:
columns = [
    'stitch_id_flat',
    'stitch_id_sterio',
    'umls_cui_from_label',
    'placebo',
    'frequency',
    'lower',
    'upper',
    'meddra_type',
    'umls_cui_from_meddra',
    'side_effect_name',
]
freq_df = pandas.read_table('download/meddra_freq.tsv.gz', names=columns)
freq_df.head(2)

,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,placebo,frequency,lower,upper,meddra_type,umls_cui_from_meddra,side_effect_name
0,CID100000085,CID000010917,C0000737,NaN,21%,0.21,0.21,LLT,C0000737,Abdominal pain
1,CID100000085,CID000010917,C0000737,NaN,21%,0.21,0.21,PT,C0000737,Abdominal pain

## meddra_all_se.tsv.gz

In [9]:
columns = [
    'stitch_id_flat',
    'stitch_id_sterio',
    'umls_cui_from_label',
    'meddra_type',
    'umls_cui_from_meddra',
    'side_effect_name',
]
se_df = pandas.read_table('download/meddra_all_se.tsv.gz', names=columns)
print(se_df.shape)
se_df['pubchem_id'] = se_df.stitch_id_sterio.map(stitch_stereo_to_pubchem)
print(se_df.shape)
#se_df = drugbank_map_df.merge(se_df)
print(se_df.shape)
se_df.head(2)

(309849, 6)
(309849, 7)
(309849, 7)

,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,meddra_type,umls_cui_from_meddra,side_effect_name,pubchem_id
0,CID100000085,CID000010917,C0000729,LLT,C0000729,Abdominal cramps,10917
1,CID100000085,CID000010917,C0000729,PT,C0000737,Abdominal pain,10917

In [11]:
se_df[se_df['pubchem_id'] == 143]

,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,meddra_type,umls_cui_from_meddra,side_effect_name,pubchem_id
322,CID100000143,CID000000143,C0002170,LLT,C0002170,Alopecia,143
323,CID100000143,CID000000143,C0002170,PT,C0002170,Alopecia,143
324,CID100000143,CID000000143,C0003123,LLT,C0003123,Anorexia,143
325,CID100000143,CID000000143,C0003123,PT,C0232462,Decreased appetite,143
326,CID100000143,CID000000143,C0009450,LLT,C0009450,Infection,143
327,CID100000143,CID000000143,C0009450,PT,C0009450,Infection,143
328,CID100000143,CID000000143,C0009806,LLT,C0009806,Constipation,143
329,CID100000143,CID000000143,C0009806,PT,C0009806,Constipation,143
330,CID100000143,CID000000143,C0011603,LLT,C0011603,Dermatitis,143
331,CID100000143,CID000000143,C0011603,PT,C0011603,Dermatitis,143
332,CID100000143,CID000000143,C0011991,LLT,C0011991,Diarrhoea,143
333,CID100000143,CID000000143,C0011991,PT,C0011991,Diarrhoea,143
334,CID100000143,CID000000143,C0015230,LLT,C0015230,Rash,143
335,CID100000143,CID000000143,C0015230,PT,C0015230,Rash,143
336,CID100000143,CID000000143,C0015230,PT,C0011603,Dermatitis,143
337,CID100000143,CID000000143,C0015376,LLT,C0015376,Extravasation,143
338,CID100000143,CID000000143,C0015376,PT,C0015376,Extravasation,143
339,CID100000143,CID000000143,C0015672,LLT,C0015672,Fatigue,143
340,CID100000143,CID000000143,C0015672,PT,C0015672,Fatigue,143
341,CID100000143,CID000000143,C0015672,PT,C0004093,Asthenia,143
342,CID100000143,CID000000143,C0020517,LLT,C0020517,Hypersensitivity,143
343,CID100000143,CID000000143,C0020517,PT,C0020517,Hypersensitivity,143
344,CID100000143,CID000000143,C0023380,LLT,C0023380,Lethargy,143
345,CID100000143,CID000000143,C0023380,PT,C0023380,Lethargy,143
346,CID100000143,CID000000143,C0023530,LLT,C0023530,Leukopenia,143
347,CID100000143,CID000000143,C0023530,PT,C0023530,Leukopenia,143
348,CID100000143,CID000000143,C0027497,LLT,C0027497,Nausea,143
349,CID100000143,CID000000143,C0027497,PT,C0027497,Nausea,143
350,CID100000143,CID000000143,C0033774,LLT,C0033774,Pruritus,143
351,CID100000143,CID000000143,C0033774,PT,C0033774,Pruritus,143
352,CID100000143,CID000000143,C0036572,LLT,C0036572,Convulsion,143
353,CID100000143,CID000000143,C0036572,PT,C0036572,Convulsion,143
354,CID100000143,CID000000143,C0038362,LLT,C0038362,Stomatitis,143
355,CID100000143,CID000000143,C0038362,PT,C0038362,Stomatitis,143
356,CID100000143,CID000000143,C0040034,LLT,C0040034,Thrombocytopenia,143
357,CID100000143,CID000000143,C0040034,PT,C0040034,Thrombocytopenia,143
358,CID100000143,CID000000143,C0041834,LLT,C0041834,Erythema,143
359,CID100000143,CID000000143,C0041834,PT,C0041834,Erythema,143
360,CID100000143,CID000000143,C0042109,LLT,C0042109,Urticaria,143
361,CID100000143,CID000000143,C0042109,PT,C0042109,Urticaria,143
362,CID100000143,CID000000143,C0042963,LLT,C0042963,Vomiting,143
363,CID100000143,CID000000143,C0042963,PT,C0042963,Vomiting,143
364,CID100000143,CID000000143,C0043144,LLT,C0043144,Wheezing,143
365,CID100000143,CID000000143,C0043144,PT,C0043144,Wheezing,143
366,CID100000143,CID000000143,C0231218,LLT,C0231218,Malaise,143
367,CID100000143,CID000000143,C0231218,PT,C0231218,Malaise,143
368,CID100000143,CID000000143,C0231218,PT,C0234215,Discomfort,143
369,CID100000143,CID000000143,C0231218,PT,C1443060,Feeling abnormal,143
370,CID100000143,CID000000143,C0231218,PT,C2047937,Ill-defined disorder,143
371,CID100000143,CID000000143,C0340865,LLT,C0340865,Anaphylactoid reaction,143
372,CID100000143,CID000000143,C0340865,PT,C0002792,Anaphylactic shock,143
373,CID100000143,CID000000143,C0340865,PT,C0340865,Anaphylactoid reaction,143
374,CID100000143,CID000000143,C0700225,LLT,C0700225,Serum creatinine increased,143
375,CID100000143,CID000000143,C0700225,PT,C0235431,Blood creatinine increased,143
376,CID100000143,CID000000143,C0746883,LLT,C0746883,Febrile neutropenia,143
377,CID100000143,CID000000143,C0746883,PT,C0746883,Febrile neutropenia,143
378,CID100000143,CID000000143,C1325847,LLT,C1325847,Sensitisation,143
379,CID100000143,CID000000143,C1325847,PT,C1325847,Sensitisation,143
380,CID100000143,CID000000143,C2609414,LLT,C2609414,Acute kidney injury,143
381,CID100000143,CID000000143,C2609414,PT,C0022660,Renal failure acute,143

In [10]:
se_df.pubchem_id.map(pubchem_id_to_drug_name_unichem)

143

UnboundLocalError: cannot access local variable 'content' where it is not associated with a value

In [56]:
drugbank_df[drugbank_df['drugbank_id'] == 'DB08875']

     drugbank_id drugbank_name
7617     DB08875  Cabozantinib

In [65]:
drugbank_map_df[drugbank_map_df['drugbank_id'] == "DB08875"]

Empty DataFrame
Columns: [drugbank_id, pubchem_id]
Index: []

In [110]:
help(pandas.DataFrame.merge)

Help on function merge in module pandas.core.frame:

merge(self, right: 'DataFrame | Series', how: 'MergeHow' = 'inner', on: 'IndexLabel | AnyArrayLike | None' = None, left_on: 'IndexLabel | AnyArrayLike | None' = None, right_on: 'IndexLabel | AnyArrayLike | None' = None, left_index: 'bool' = False, right_index: 'bool' = False, sort: 'bool' = False, suffixes: 'Suffixes' = ('_x', '_y'), copy: 'bool | None' = None, indicator: 'str | bool' = False, validate: 'MergeValidate | None' = None) -> 'DataFrame'
    Merge DataFrame or named Series objects with a database-style join.

    A named Series object is treated as a DataFrame with a single named column.

    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.

    .. warning::

        If both key columns contain rows where the key is a null value, those
        rows will be matched against each other. This is different from usual SQL
        join behaviour and can lead to unexpected results.

    Parameters
    ----------
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
        Type of merge to be performed.

        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key order.
        * outer: use union of keys from both frames, similar to a SQL full outer
          join; sort keys lexicographically.
        * inner: use intersection of keys from both frames, similar to a SQL inner
          join; preserve the order of the left keys.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.
    on : label or list
        Column or index level names to join on. These must be found in both
        DataFrames. If `on` is None and not merging on indexes then this defaults
        to the intersection of the columns in both DataFrames.
    left_on : label or list, or array-like
        Column or index level names to join on in the left DataFrame. Can also
        be an array or list of arrays of the length of the left DataFrame.
        These arrays are treated as if they are columns.
    right_on : label or list, or array-like
        Column or index level names to join on in the right DataFrame. Can also
        be an array or list of arrays of the length of the right DataFrame.
        These arrays are treated as if they are columns.
    left_index : bool, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels.
    right_index : bool, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index.
    sort : bool, default False
        Sort the join keys lexicographically in the result DataFrame. If False,
        the order of the join keys depends on the join type (how keyword).
    suffixes : list-like, default is ("_x", "_y")
        A length-2 sequence where each element is optionally a string
        indicating the suffix to add to overlapping column names in
        `left` and `right` respectively. Pass a value of `None` instead
        of a string to indicate that the column name from `left` or
        `right` should be left as-is, with no suffix. At least one of the
        values must not be None.
    copy : bool, default True
        If False, avoid copy if possible.

        .. note::
            The `copy` keyword will change behavior in pandas 3.0.
            `Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            will be enabled by default, which means that all methods with a
            `copy` keyword will use a lazy copy mechanism to defer the copy and
            ignore the `copy` keyword. The `copy` keyword will be removed in a
            future version of pandas.

            You can already get the future behavior and improvements through
            enabling copy on write ``pd.options.mode.copy_on_write = True``
    indicator : bool or str, default False
        If True, adds a column to the output DataFrame called "_merge" with
        information on the source of each row. The column can be given a different
        name by providing a string argument. The column will have a Categorical
        type with the value of "left_only" for observations whose merge key only
        appears in the left DataFrame, "right_only" for observations
        whose merge key only appears in the right DataFrame, and "both"
        if the observation's merge key is found in both DataFrames.

    validate : str, optional
        If specified, checks if merge is of specified type.

        * "one_to_one" or "1:1": check if merge keys are unique in both
          left and right datasets.
        * "one_to_many" or "1:m": check if merge keys are unique in left
          dataset.
        * "many_to_one" or "m:1": check if merge keys are unique in right
          dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A DataFrame of the two merged objects.

    See Also
    --------
    merge_ordered : Merge with optional filling/interpolation.
    merge_asof : Merge on nearest keys.
    DataFrame.join : Similar method using indices.

    Examples
    --------
    >>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [1, 2, 3, 5]})
    >>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [5, 6, 7, 8]})
    >>> df1
        lkey value
    0   foo      1
    1   bar      2
    2   baz      3
    3   foo      5
    >>> df2
        rkey value
    0   foo      5
    1   bar      6
    2   baz      7
    3   foo      8

    Merge df1 and df2 on the lkey and rkey columns. The value columns have
    the default suffixes, _x and _y, appended.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey')
      lkey  value_x rkey  value_y
    0  foo        1  foo        5
    1  foo        1  foo        8
    2  bar        2  bar        6
    3  baz        3  baz        7
    4  foo        5  foo        5
    5  foo        5  foo        8

    Merge DataFrames df1 and df2 with specified left and right suffixes
    appended to any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey',
    ...           suffixes=('_left', '_right'))
      lkey  value_left rkey  value_right
    0  foo           1  foo            5
    1  foo           1  foo            8
    2  bar           2  bar            6
    3  baz           3  baz            7
    4  foo           5  foo            5
    5  foo           5  foo            8

    Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
    any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
    Traceback (most recent call last):
    ...
    ValueError: columns overlap but no suffix specified:
        Index(['value'], dtype='object')

    >>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
    >>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
    >>> df1
          a  b
    0   foo  1
    1   bar  2
    >>> df2
          a  c
    0   foo  3
    1   baz  4

    >>> df1.merge(df2, how='inner', on='a')
          a  b  c
    0   foo  1  3

    >>> df1.merge(df2, how='left', on='a')
          a  b  c
    0   foo  1  3.0
    1   bar  2  NaN

    >>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
    >>> df2 = pd.DataFrame({'right': [7, 8]})
    >>> df1
        left
    0   foo
    1   bar
    >>> df2
        right
    0   7
    1   8

    >>> df1.merge(df2, how='cross')
       left  right
    0   foo      7
    1   foo      8
    2   bar      7
    3   bar      8

In [117]:
# se_df['drugbank_id'] = 
se_df.pubchem_id.map(pubchem_id_to_drug_name_unichem)

143

UnboundLocalError: cannot access local variable 'content' where it is not associated with a value

In [60]:
se_df = se_df.merge(drugbank_df, how='left')
# se_df = se_df[['drugbank_id', 'umls_cui_from_meddra', 'side_effect_name']]
se_df

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [25]:
se_df[se_df['umls_cui_from_meddra'] == 'C1145670'].sort_values(by='drugbank_id').drop

,drugbank_id,pubchem_id,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,meddra_type,umls_cui_from_meddra,side_effect_name
35765,DB00181,2284,CID100002284,CID000002284,C3203358,PT,C1145670,Respiratory failure
15117,DB00184,89594,CID100000942,CID000089594,C1145670,PT,C1145670,Respiratory failure
15116,DB00184,89594,CID100000942,CID000089594,C1145670,LLT,C1145670,Respiratory failure
123563,DB00186,3958,CID100003958,CID000003958,C3203358,PT,C1145670,Respiratory failure
123554,DB00186,3958,CID100003958,CID000003958,C1145670,LLT,C1145670,Respiratory failure
...,...,...,...,...,...,...,...,...
348325,NaN,25102847,CID125102847,CID025102847,C1145670,PT,C1145670,Respiratory failure
351931,NaN,70683024,CID170683024,CID070683024,C1145670,LLT,C1145670,Respiratory failure
351932,NaN,70683024,CID170683024,CID070683024,C1145670,PT,C1145670,Respiratory failure
352629,NaN,71306834,CID171306834,CID071306834,C0035229,PT,C1145670,Respiratory failure
353109,NaN,71306834,CID171306834,CID071306834,C3203358,PT,C1145670,Respiratory failure

In [17]:
se_df = se_df.dropna()
se_df

,drugbank_id,pubchem_id,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,meddra_type,umls_cui_from_meddra,side_effect_name
0,DB00583,10917,CID100000085,CID000010917,C0000729,LLT,C0000729,Abdominal cramps
1,DB02648,10917,CID100000085,CID000010917,C0000729,LLT,C0000729,Abdominal cramps
2,DB00583,10917,CID100000085,CID000010917,C0000729,PT,C0000737,Abdominal pain
3,DB02648,10917,CID100000085,CID000010917,C0000729,PT,C0000737,Abdominal pain
4,DB00583,10917,CID100000085,CID000010917,C0000737,LLT,C0000737,Abdominal pain
...,...,...,...,...,...,...,...,...
351857,DB00159,56842239,CID156842239,CID056842239,C0162429,LLT,C0162429,Malnutrition
351858,DB03756,56842239,CID156842239,CID056842239,C0162429,LLT,C0162429,Malnutrition
351859,DB00132,56842239,CID156842239,CID056842239,C0162429,PT,C0162429,Malnutrition
351860,DB00159,56842239,CID156842239,CID056842239,C0162429,PT,C0162429,Malnutrition
351861,DB03756,56842239,CID156842239,CID056842239,C0162429,PT,C0162429,Malnutrition

In [49]:
se_df[(se_df['umls_cui_from_meddra'] == 'C1145670') & (se_df['pubchem_id'] == 25102847)]

,drugbank_id,pubchem_id,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,meddra_type,umls_cui_from_meddra,side_effect_name
348324,NaN,25102847,CID125102847,CID025102847,C1145670,LLT,C1145670,Respiratory failure
348325,NaN,25102847,CID125102847,CID025102847,C1145670,PT,C1145670,Respiratory failure

In [26]:
side_effect_MS = se_df[se_df['umls_cui_from_meddra'] == 'C1145670'].query("meddra_type == 'PT'")

In [43]:
side_effect_MS.merge(drugbank_df).drop_duplicates(subset='drugbank_id').sort_values(['drugbank_name']).drop_duplicates(subset=['drugbank_name'])['drugbank_name'].to_csv("drugbank_name.csv")

In [44]:
side_effect_MS['drugbank_id']

359       DB00855
1957      DB00194
1958      DB00640
1959      DB03528
2116      DB02379
           ...
337755    DB08865
348325        NaN
351932        NaN
352629        NaN
353109        NaN
Name: drugbank_id, Length: 194, dtype: object

In [92]:
side_effect_MS.columns

Index(['stitch_id_flat', 'stitch_id_sterio', 'umls_cui_from_label',
       'meddra_type', 'umls_cui_from_meddra', 'side_effect_name',
       'pubchem_id'],
      dtype='object')

In [99]:
side_effect_MS['name'] = side_effect_MS.apply(stitch_id_to_drug_name, axis=1)

[{"taxonName":"small molecule","queryIndex":0,"ncbiTaxonId":-1,"annotation":"cevimeline","preferredName":"cevimeline","stringId":"-1.CID100002684"}]
[{"taxonName":"small molecule","annotation":"imiquimod","ncbiTaxonId":-1,"queryIndex":0,"stringId":"-1.CID100057469","preferredName":"imiquimod"}]
[{"preferredName":"pregabalin","ncbiTaxonId":-1,"annotation":"pregabalin","queryIndex":0,"stringId":"-1.CID100125889","taxonName":"small molecule"}]
[{"annotation":"varenicline","taxonName":"small molecule","preferredName":"varenicline","queryIndex":0,"ncbiTaxonId":-1,"stringId":"-1.CID100170361"}]
<!DOCTYPE html>

<head>
<meta http-equiv='Content-type' content='text/html;charset=UTF-8' />
<link rel='shortcut icon' href='/images/favicon.png' />
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'/>
<link href='https://fonts.googleapis.com/css?family=Raleway:400,300,500,700' rel='stylesheet' type='text/css'/>
<title>STITCH: chemical association networks</title>
<script type='text/javascript'>
//<![CDATA[

var js_comm_globals = {web_cgi_dir: '/cgi', web_images_dir: '/images',
                       user_id: 'XSEahfMWAx09', task_id: 'UoUTFWCzO1pN', session_id: 'qFxLJfy83Bqd',
                       targetmode: 'proteins', calling_script: 'webservice_handler.pl',
                      };

//]]>
</script>
<script type='text/javascript' src='/javascript/navigation_and_popup_functions_7023.js'></script>
<script type='text/javascript' src='/javascript/string_scripts_7023.js'></script>
<script type='text/javascript' src='/javascript/jquery/jquery-1.7.1.min.js'></script><script type='text/javascript' src='/javascript/basic/basic_js_util_7023.js'></script>
<script type='text/javascript' src='/javascript/basic/basic_ajax_7023.js'></script>
<script type='text/javascript' src='/javascript/basic/basic_floating_div_7023.js'></script>
<script type='text/javascript' src='/javascript/ac_oetags.js'></script>
<link href='/css/floatingDiv.css' rel='stylesheet' type='text/css'/>
<link href='/css/main_stylesheet_pc.v7267.css' rel='stylesheet' type='text/css'/>
</head>

<body id="stringBodyTag" onclick="hideFDifInside('fpWindowDiv');hideFDifInside('LinkWindowDiv');hideFDifInside('pageLoadFloatingDiv');" onmousedown="hideFDifInside('fpWindowDiv');hideFDifInside('LinkWindowDiv');hideFDifInside('pageLoadFloatingDiv');" >
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-2456420-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<div style='position:absolute;' class='nodeInfoDivStyle' id='fpWindowDiv' onmouseout='signalFDOnMouseOut(event, this, "fpWindowDiv"); restoreFNButtonMode (event, this); window.status=""; return true;'></div>
<div style='position:absolute;' class='nodeInfoDivStyle' id='LinkWindowDiv' onmouseout='signalFDOnMouseOut(event, this, "LinkWindowDiv"); restoreFNButtonMode (event, this); window.status=""; return true;'><div id="containerInnerLink"></div><b>Full Link:</b><textarea cols='50' rows='6' style='border:none;border-radius:3px;width:100%;'>http://version_5_0.stitch-db.org/cgi/webservice_handler.pl?all_channels_on=1&amp;targetmode=proteins&amp;identifier=&amp;species=auto_detect</textarea></div>
<script type='text/javascript'> $("#fpWindowDiv").mouseenter(function() {signalFDOnMouseIn("fpWindowDiv"); });</script>
<script type='text/javascript'> $("#LinkWindowDiv").mouseenter(function() {signalFDOnMouseIn("LinkWindowDiv"); });</script>
<div class='top_bar'>
<div class='container'>
<div class='left'>
<ul class='top_bar_list'>
<li class='header'>Version:</li>
<li class='last'>5.0</li>
</ul>
</div>
<div class='right'>
<ul class='top_bar_list'>
<li><a href='/cgi/my.pl?UserId=XSEahfMWAx09&amp;sessionId=qFxLJfy83Bqd'>Login</a></li>
<li><a href='/cgi/register.pl?UserId=XSEahfMWAx09&amp;sessionId=qFxLJfy83Bqd'>Register</a></li>
</ul>
</div>
</div>
</div>
<div class='main_header'>
<div class='container'>
<h1 style='line-height: 2em;'><a id='stitch_logo' href='/cgi/input.pl?UserId=XSEahfMWAx09&amp;sessionId=qFxLJfy83Bqd'>STITCH</a></h1><div class='main_nav'>
<ul>
<li><div class='main_nav_item input_switch_to_search'><a href='/cgi/input.pl?UserId=XSEahfMWAx09&amp;sessionId=qFxLJfy83Bqd&amp;input_page_show_search=on' class='main_nav_item input_switch_to_search' id='search' onclick='main_nav_click (document.getElementById("search")); return true;'>Search</a></div></li>
<li><div class='main_nav_item'><a href='/cgi/download.pl?UserId=XSEahfMWAx09&amp;sessionId=qFxLJfy83Bqd' class='main_nav_item' onclick='main_nav_click(this); return true;'>Download</a></div></li>
<li><div class='main_nav_item'><a href='/cgi/help.pl?UserId=XSEahfMWAx09&amp;sessionId=qFxLJfy83Bqd' class='main_nav_item' onclick='main_nav_click(this); return true;'>Help</a></div></li>
<li><div class='main_nav_item'><a href='/cgi/my.pl?UserId=XSEahfMWAx09&amp;sessionId=qFxLJfy83Bqd' class='main_nav_item' onclick='main_nav_click(this); return true;'>My&nbsp;Data</a></div></li>
</ul>
</div><!-- end main_nav -->
</div>
<div class='shadow'></div>
</div>
<script type='text/javascript'>
<!--
//-->
</script>
<noscript>
</noscript>
Content-type:text/json
Status: 400 Bad Request

{ "Error" : "No interactions found", "ErrorMessage" : "This chemical does not have an interaction in any species."  }

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### DataFrame Functions: Cross Reference Other ID formats Given pubchem_id

In [51]:
def pubchem_id_to_drug_name(cid):
    import requests

    # cid = str(row['pubchem_id'])  # Replace with your CID
    url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{cid}/synonyms/JSON"
    
    response = requests.get(url)
    data = response.json()
    first_synonym = data['InformationList']['Information'][0]['Synonym'][0]

    return first_synonym

In [79]:
import requests
# source_compound_id = 25102847
url = f"https://www.ebi.ac.uk/unichem/api/v1/compounds"
parameter = {
          "compound": "25102847",
          "sourceID": 22,
          "type": "sourceID"
        }
response = requests.get(url, params=parameter)
data = response.json()

In [2]:
def pubchem_id_to_drug_name_unichem(uci):
    url = "https://www.ebi.ac.uk/unichem/api/v1/compounds"
    data = {
        "compound": uci,
        "sourceID": 22,
        "type": "sourceID"
    }
    
    response = requests.post(url, json=data)
    if response.status_code == 200:
        try:
            content = response.json()['compounds'][0]['sources']
        except:
            print(uci)
        for i in content:
            if i['id'] == 45:
                name = [i['compoundId']]
                return name[0]
        return None
    else:
        return None

In [106]:
pubchem_id_to_drug_name_unichem("25102847")

'CABOZANTINIB'

In [83]:
import requests

url = "https://www.ebi.ac.uk/unichem/api/v1/compounds"
# headers = {
#     "accept": "application/json",
#     "Content-Type": "application/json"
# }
data = {
    "compound": "25102847",
    "sourceID": 22,
    "type": "sourceID"
}

response = requests.post(url, json=data)

In [104]:
content = response.json()['compounds'][0]['sources']
# for i in content:
#     if i['id'] == 45:
#         print(i['compoundId'])
print([i['compoundId'] for i in content if i['id'] == 45])

['CABOZANTINIB']

#### Some InChIKey doesn't have corresponding ChEMBL ID

In [73]:
def pubchem_id_to_InChIKey_to_ChEMBL_ID(row):
    import requests

    cid = int(row['pubchem_id'])  # Replace with your CID
    url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{cid}/property/InChI,InChIKey/JSON"

    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
    else:
        print(cid)
    try:
        InChIKey = data['PropertyTable']['Properties'][0]['InChIKey']
    except KeyError:
        print(data)
    # print(InChIKey)
    url = f"https://www.ebi.ac.uk/unichem/rest/inchikey/{InChIKey}"
    response = requests.get(url)
    data = response.json()

    Unichem_df = pd.DataFrame(data)
    if '1' in Unichem_df['src_id'].to_list():
        chembl_id_object = Unichem_df[Unichem_df['src_id'] == '1']['src_compound_id']
    # print(Unichem_df)
        chembl_id = chembl_id_object.values[0]
    else:
        chembl_id = None
    return chembl_id

In [29]:
side_effect_MS['drug_name'] = side_effect_MS.apply(pubchem_id_to_drug_name, axis=1)
side_effect_MS

,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,meddra_type,umls_cui_from_meddra,side_effect_name,pubchem_id,drug_name
38739,CID100002684,CID000083898,C0026769,PT,C0026769,Multiple sclerosis,83898,Cevimeline
211095,CID100057469,CID000057469,C0026769,PT,C0026769,Multiple sclerosis,57469,IMIQUIMOD
216046,CID100060754,CID000060754,C0026769,PT,C0026769,Multiple sclerosis,60754,Gadodiamide hydrate
247264,CID100125889,CID005486971,C0026769,PT,C0026769,Multiple sclerosis,5486971,Pregabalin
259034,CID100170361,CID000170361,C0026769,PT,C0026769,Multiple sclerosis,170361,Varenicline
299280,CID116131310,CID016131310,C0026769,PT,C0026769,Multiple sclerosis,16131310,Heplisav
307569,CID154677977,CID054684141,C0026769,PT,C0026769,Multiple sclerosis,54684141,Teriflunomide

#### For unavailable ChEMBL IDs, we can either impute manually or use code snippet from ATC to ChEMBL jupyter notebook to search the drug name in ChEMBL.

In [48]:
side_effect_MS['ChEMBL_ID'] = side_effect_MS.apply(pubchem_id_to_InChIKey_to_ChEMBL_ID, axis=1)
side_effect_MS

,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,meddra_type,umls_cui_from_meddra,side_effect_name,pubchem_id,drug_name,ChEMBL_ID
38739,CID100002684,CID000083898,C0026769,PT,C0026769,Multiple sclerosis,83898,Cevimeline,CHEMBL1201267
211095,CID100057469,CID000057469,C0026769,PT,C0026769,Multiple sclerosis,57469,IMIQUIMOD,CHEMBL1282
216046,CID100060754,CID000060754,C0026769,PT,C0026769,Multiple sclerosis,60754,Gadodiamide hydrate,None
247264,CID100125889,CID005486971,C0026769,PT,C0026769,Multiple sclerosis,5486971,Pregabalin,CHEMBL1059
259034,CID100170361,CID000170361,C0026769,PT,C0026769,Multiple sclerosis,170361,Varenicline,CHEMBL1396
299280,CID116131310,CID016131310,C0026769,PT,C0026769,Multiple sclerosis,16131310,Heplisav,None
307569,CID154677977,CID054684141,C0026769,PT,C0026769,Multiple sclerosis,54684141,Teriflunomide,CHEMBL973

In [9]:
import requests

cid = "54684141"  # Replace with your CID
url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{cid}/synonyms/JSON"

response = requests.get(url)
data = response.json()
synonym_first = data['InformationList']['Information'][0]['Synonym'][0]

'Teriflunomide'

In [11]:
import requests

cid = "54684141"  # Replace with your CID
url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{cid}/property/InChI,InChIKey/JSON"

response = requests.get(url)
data = response.json()
data['PropertyTable']['Properties'][0]['InChIKey']
# Example: print out the compound's name and molecular formula
# print("Name:", data['PropertyTable']['Properties'][0]['IUPACName'])
# print("Molecular Formula:", data['PropertyTable']['Properties'][0]['MolecularFormula'])

'UTNUDOFZCWSZMS-YFHOEESVSA-N'

In [12]:
import requests

InChIKey = 'UTNUDOFZCWSZMS-YFHOEESVSA-N'
url = f"https://www.ebi.ac.uk/unichem/rest/inchikey/{InChIKey}"

response = requests.get(url)

In [13]:
data = response.json()

In [14]:
data

[{'src_id': '7', 'src_compound_id': '68540'},
 {'src_id': '14', 'src_compound_id': '1C058IKG3B'},
 {'src_id': '21', 'src_compound_id': '15221873'},
 {'src_id': '22', 'src_compound_id': '54684141'},
 {'src_id': '49', 'src_compound_id': 'PD010419'},
 {'src_id': '26', 'src_compound_id': '108605-62-5'},
 {'src_id': '3', 'src_compound_id': 'A26'},
 {'src_id': '15', 'src_compound_id': 'SCHEMBL22661'},
 {'src_id': '9', 'src_compound_id': 'ZINC000013512456'},
 {'src_id': '39', 'src_compound_id': 'CB5648113'},
 {'src_id': '40', 'src_compound_id': 'teriflunomide'},
 {'src_id': '32', 'src_compound_id': 'DTXSID80893457'},
 {'src_id': '39', 'src_compound_id': 'CB02486749'},
 {'src_id': '39', 'src_compound_id': 'CB6464433'},
 {'src_id': '2', 'src_compound_id': 'DB08880'},
 {'src_id': '37', 'src_compound_id': '55910'},
 {'src_id': '37', 'src_compound_id': '163092'},
 {'src_id': '37', 'src_compound_id': '6758'},
 {'src_id': '37', 'src_compound_id': '147806'},
 {'src_id': '36', 'src_compound_id': 'MTBLC68540'},
 {'src_id': '10', 'src_compound_id': '26948188'},
 {'src_id': '5', 'src_compound_id': '12014666'},
 {'src_id': '1', 'src_compound_id': 'CHEMBL973'},
 {'src_id': '29', 'src_compound_id': 'J690.639G'},
 {'src_id': '45', 'src_compound_id': 'TERIFLUNOMIDE'},
 {'src_id': '4', 'src_compound_id': '6844'},
 {'src_id': '29', 'src_compound_id': 'J994.777I'},
 {'src_id': '46', 'src_compound_id': 'A77 1726'},
 {'src_id': '46', 'src_compound_id': 'HMR1726'},
 {'src_id': '46', 'src_compound_id': 'TERIFLUNOMIDE'},
 {'src_id': '46', 'src_compound_id': 'AUBAGIO'},
 {'src_id': '46', 'src_compound_id': 'HMR-1726'},
 {'src_id': '31', 'src_compound_id': '50018011'},
 {'src_id': '47', 'src_compound_id': 'AUBAGIO'},
 {'src_id': '34', 'src_compound_id': '4634'},
 {'src_id': '50', 'src_compound_id': 'DOSCUM'},
 {'src_id': '47', 'src_compound_id': 'TERIFLUNOMIDE'}]

In [4]:
import pandas as pd

In [33]:
Unichem_df = pd.DataFrame(data)
chembl_id = Unichem_df[Unichem_df['src_id'] == '1']['src_compound_id']
chembl_id.values[0]

'CHEMBL973'

In [116]:
data

{'InformationList': {'Information': [{'CID': 54684141,
    'Synonym': ['Teriflunomide',
     '163451-81-8',
     '108605-62-5',
     'Aubagio',
     'Flucyamide',
     'A77 1726',
     'HMR1726',
     '(Z)-2-Cyano-3-hydroxy-N-(4-(trifluoromethyl)phenyl)but-2-enamide',
     'HMR 1726',
     'HMR-1726',
     'SU 20',
     'A 771726',
     'A-771726',
     'A771726',
     'teriflunomida',
     'teriflunomidum',
     'A 77-1726',
     'CHEBI:68540',
     'UNII-1C058IKG3B',
     '1C058IKG3B',
     '2-cyano-3-hydroxy-N-(4-(trifluoromethyl)phenyl)but-2-enamide',
     '(E/Z)-Teriflunomide',
     '(Z)-2-cyano-3-hydroxy-N-[4-(trifluoromethyl)phenyl]but-2-enamide',
     '(Z)-2-cyano-alpha,alpha,alpha-trifluoro-3-hydroxy-p-crotonotoluidide',
     'N-(4-Trifluoromethylphenyl)-2-cyano-2-hydroxycrotonamide',
     '2-hydroxyethylidene-cyanoacetic acid-4-trifluoromethyl anilide',
     'A 1726',
     '(2z)-2-Cyano-3-Hydroxy-N-[4-(Trifluoromethyl)phenyl]but-2-Enamide',
     '2-Butenamide, 2-cyano-3-hydroxy-N-[4-(trifluoromethyl)phenyl]-, (2Z)-',
     '2-Butenamide, 2-cyano-3-hydroxy-N-(4-(trifluoromethyl)phenyl)-',
     'DTXSID80893457',
     'A77-1726',
     'Teriflunomide (USAN)',
     'Teriflunomide [INN]',
     '2-Butenamide, 2-cyano-3-hydroxy-N-[4-(trifluoromethyl)phenyl]-',
     '2-Cyano-3-hydroxy-N-(4-(trifluoromethyl)phenyl)-2-butenamide',
     'TERIFLUNOMIDE [USAN]',
     'TERIFLUNOMIDE (EP MONOGRAPH)',
     'TERIFLUNOMIDE [EP MONOGRAPH]',
     '(Z)-2-cyano-3-hydroxy-N-(4-(trifluoromethyl)phenyl)-2-butenamide',
     '(Z)-2-cyano-3-hydroxy-N-(4-(trifluoromethyl)phenyl)but-2-enamide.',
     'MFCD00910058',
     'RS 61980',
     '2-Butenamide, 2-cyano-3-hydroxy-N-(4-(trifluoromethyl)phenyl)-, (Z)-',
     '2-BUTENAMIDE, 2-CYANO-3-HYDROXY-N-(4-(TRIFLUOROMETHYL)PHENYL)-, (2Z)-',
     'LEFLUNOMIDE IMPURITY B (EP IMPURITY)',
     'LEFLUNOMIDE IMPURITY B [EP IMPURITY]',
     'Teriflunomide [USAN:INN]',
     'A77 1726 (E/Z) Mixture',
     '2-cyano-3-hydroxy-N-[4-(trifluoromethyl)phenyl]but-2-enamide',
     'Teriflunomide(Random Configuration)',
     '(2Z)-2-cyano-3-hydroxy-N-(4-(trifluoromethyl)phenyl)but-2-enamide',
     '(Z)-2-Cyano-3-hydroxy-N-[4-(trifluoromethyl)phenyl]-2-butenamide',
     'A26',
     'Aubagio (TN)',
     'SU-0020',
     'RS-61980',
     "(Z)-2-Cyano-alpha'alpha'alpha-trifluoro-3-hydroxy-p-crotonotoluidide",
     'TERIFLUNOMIDE [MI]',
     '(2Z)-2-[hydroxy-[4-(trifluoromethyl)anilino]methylidene]-3-oxobutanenitrile',
     'DIMETHYL APROBARBITAL',
     'SCHEMBL22661',
     'TERIFLUNOMIDE [VANDF]',
     'Teriflunomide, A77 1726',
     'TERIFLUNOMIDE [WHO-DD]',
     'Teriflunomide(A-771726)?',
     '2-Cyano-3-OH-N-(4-trifluoromethylphenyl)croton amide',
     'GTPL6844',
     'L04AA31',
     'DTXCID401323471',
     'GLXC-04382',
     'TERIFLUNOMIDE [ORANGE BOOK]',
     '(2Z)-2-cyano-3-hydroxy-N-(4-(trifluoromethyl)phenyl)-2-butenamide',
     'BDBM50018011',
     'NSC766118',
     's4169',
     'AKOS015994773',
     'CCG-267145',
     'DB08880',
     'LE-0275',
     'NSC-766118',
     'NCGC00263218-07',
     'NCGC00263218-13',
     'AC-26446',
     'DA-78329',
     'HY-110159',
     'CS-0033021',
     'SW219377-1',
     'T3287',
     'D10172',
     'EN300-189832',
     'AB01565775_02',
     'A801897',
     'A882574',
     'J-010046',
     'Q3077133',
     'N-(4-trifluoromethylphenyl)-2-cyano-3-hydroxycrotonamide',
     'Z1878131003',
     'N-[4-(Trifluoromethyl)phenyl]-2-cyano-3-hydroxycrotonamide',
     '2-cyano-3-hydroxy-N-[4-(trifluoromethyl)phenyl]-2Z-butenamide',
     'A 77-1726;A771726;HMR1726;CAS# 108605-62-5',
     '(2Z)-2-Cyano-3-hydroxy-N-[4-(trifluoromethyl)phenyl]but-2-enamide (Teriflunomide)',
     'A 1726, A77-1726, A771726, Flucyamide, HMR 1726, N-(4-Trifluoromethylphenyl)-2-cyano-3-hydroxycrotoamide, SU 20']}]}}

In [10]:
se_df[se_df['umls_cui_from_label'] == 'C0235431']

,drugbank_id,pubchem_id,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,meddra_type,umls_cui_from_meddra,side_effect_name
4206,DB00177,60846,CID100005650,CID000060846,C0235431,LLT,C0235431,Blood creatinine increased
4207,DB00177,60846,CID100005650,CID000060846,C0235431,PT,C0235431,Blood creatinine increased
9818,DB00193,33741,CID100005523,CID000033741,C0235431,LLT,C0235431,Blood creatinine increased
9819,DB00193,33741,CID100005523,CID000033741,C0235431,PT,C0235431,Blood creatinine increased
17910,DB00218,101526,CID100004259,CID000101526,C0235431,LLT,C0235431,Blood creatinine increased
...,...,...,...,...,...,...,...,...
297492,DB08889,11556711,CID111556711,CID011556711,C0235431,PT,C0235431,Blood creatinine increased
298657,DB08907,24812758,CID124812758,CID024812758,C0235431,LLT,C0235431,Blood creatinine increased
298658,DB08907,24812758,CID124812758,CID024812758,C0235431,PT,C0235431,Blood creatinine increased
298917,DB08910,134780,CID100134780,CID000134780,C0235431,LLT,C0235431,Blood creatinine increased
298918,DB08910,134780,CID100134780,CID000134780,C0235431,PT,C0235431,Blood creatinine increased

In [11]:
se_df[(se_df['umls_cui_from_label'] == 'C0235431') & (se_df['meddra_type'] == 'PT')]

,drugbank_id,pubchem_id,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,meddra_type,umls_cui_from_meddra,side_effect_name
4207,DB00177,60846,CID100005650,CID000060846,C0235431,PT,C0235431,Blood creatinine increased
9819,DB00193,33741,CID100005523,CID000033741,C0235431,PT,C0235431,Blood creatinine increased
17911,DB00218,101526,CID100004259,CID000101526,C0235431,PT,C0235431,Blood creatinine increased
19090,DB00225,60754,CID100060754,CID000060754,C0235431,PT,C0235431,Blood creatinine increased
20676,DB00230,5486971,CID100125889,CID005486971,C0235431,PT,C0235431,Blood creatinine increased
...,...,...,...,...,...,...,...,...
294191,DB08816,9871419,CID109871419,CID009871419,C0235431,PT,C0235431,Blood creatinine increased
294464,DB08822,11238823,CID111238823,CID011238823,C0235431,PT,C0235431,Blood creatinine increased
297492,DB08889,11556711,CID111556711,CID011556711,C0235431,PT,C0235431,Blood creatinine increased
298658,DB08907,24812758,CID124812758,CID024812758,C0235431,PT,C0235431,Blood creatinine increased
298918,DB08910,134780,CID100134780,CID000134780,C0235431,PT,C0235431,Blood creatinine increased

In [12]:
se_df[(se_df['umls_cui_from_label'] == 'C0235431') & (se_df['meddra_type'] == 'LLT')]

,drugbank_id,pubchem_id,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,meddra_type,umls_cui_from_meddra,side_effect_name
4206,DB00177,60846,CID100005650,CID000060846,C0235431,LLT,C0235431,Blood creatinine increased
9818,DB00193,33741,CID100005523,CID000033741,C0235431,LLT,C0235431,Blood creatinine increased
17910,DB00218,101526,CID100004259,CID000101526,C0235431,LLT,C0235431,Blood creatinine increased
19089,DB00225,60754,CID100060754,CID000060754,C0235431,LLT,C0235431,Blood creatinine increased
20675,DB00230,5486971,CID100125889,CID005486971,C0235431,LLT,C0235431,Blood creatinine increased
...,...,...,...,...,...,...,...,...
294190,DB08816,9871419,CID109871419,CID009871419,C0235431,LLT,C0235431,Blood creatinine increased
294463,DB08822,11238823,CID111238823,CID011238823,C0235431,LLT,C0235431,Blood creatinine increased
297491,DB08889,11556711,CID111556711,CID011556711,C0235431,LLT,C0235431,Blood creatinine increased
298657,DB08907,24812758,CID124812758,CID024812758,C0235431,LLT,C0235431,Blood creatinine increased
298917,DB08910,134780,CID100134780,CID000134780,C0235431,LLT,C0235431,Blood creatinine increased

In [13]:
se_df[se_df['umls_cui_from_meddra'] == 'C0235431']

,drugbank_id,pubchem_id,stitch_id_flat,stitch_id_sterio,umls_cui_from_label,meddra_type,umls_cui_from_meddra,side_effect_name
1362,DB00091,5280754,CID100002909,CID005280754,C0151578,PT,C0235431,Blood creatinine increased
1506,DB00091,5280754,CID100002909,CID005280754,C0700225,PT,C0235431,Blood creatinine increased
2587,DB00136,5280453,CID100002524,CID005280453,C0700225,PT,C0235431,Blood creatinine increased
4206,DB00177,60846,CID100005650,CID000060846,C0235431,LLT,C0235431,Blood creatinine increased
4207,DB00177,60846,CID100005650,CID000060846,C0235431,PT,C0235431,Blood creatinine increased
...,...,...,...,...,...,...,...,...
298917,DB08910,134780,CID100134780,CID000134780,C0235431,LLT,C0235431,Blood creatinine increased
298918,DB08910,134780,CID100134780,CID000134780,C0235431,PT,C0235431,Blood creatinine increased
299127,DB08911,11707110,CID111707110,CID011707110,C0151578,PT,C0235431,Blood creatinine increased
299417,DB08912,44462760,CID144462760,CID044462760,C0151578,PT,C0235431,Blood creatinine increased
300143,DB08930,46216142,CID146216142,CID046216142,C0700225,PT,C0235431,Blood creatinine increased

In [14]:
se_df = se_df[['drugbank_id', 'umls_cui_from_meddra', 'side_effect_name']]
se_df = se_df.dropna()
se_df = se_df.drop_duplicates(['drugbank_id', 'umls_cui_from_meddra'])
se_df = drugbank_df.merge(se_df)
se_df = se_df.sort_values(['drugbank_name', 'side_effect_name'])
len(se_df)

153663

In [15]:
se_df

,drugbank_id,drugbank_name,umls_cui_from_meddra,side_effect_name
146269,DB07768,"(10ALPHA,13ALPHA,14BETA,17ALPHA)-17-HYDROXYAND...",C0000729,Abdominal cramps
146270,DB07768,"(10ALPHA,13ALPHA,14BETA,17ALPHA)-17-HYDROXYAND...",C0000737,Abdominal pain
146524,DB07768,"(10ALPHA,13ALPHA,14BETA,17ALPHA)-17-HYDROXYAND...",C0232492,Abdominal pain upper
146622,DB07768,"(10ALPHA,13ALPHA,14BETA,17ALPHA)-17-HYDROXYAND...",C0740651,Abdominal symptom
146645,DB07768,"(10ALPHA,13ALPHA,14BETA,17ALPHA)-17-HYDROXYAND...",C0877331,Abnormal clotting factor
...,...,...,...,...
138639,DB05738,vapitadine dihydrochloride,C0015230,Rash
138654,DB05738,vapitadine dihydrochloride,C0234233,Tenderness
138650,DB05738,vapitadine dihydrochloride,C0041582,Ulcer
138651,DB05738,vapitadine dihydrochloride,C0042487,Venous thrombosis
138652,DB05738,vapitadine dihydrochloride,C0042963,Vomiting

In [16]:
# Create a reference of side effect IDs and Names
se_terms_df = se_df[['umls_cui_from_meddra', 'side_effect_name']].drop_duplicates()
assert se_terms_df.side_effect_name.duplicated().sum() == 0
se_terms_df = se_terms_df.sort_values('side_effect_name')
se_terms_df.to_csv('side-effect-terms.tsv', sep='\t', index=False)

In [17]:
se_df[se_df['side_effect_name'] == 'Multiple sclerosis']

       drugbank_id drugbank_name umls_cui_from_meddra    side_effect_name
3214       DB00185    Cevimeline             C0026769  Multiple sclerosis
9584       DB00225   Gadodiamide             C0026769  Multiple sclerosis
63677      DB00724     Imiquimod             C0026769  Multiple sclerosis
10096      DB00230    Pregabalin             C0026769  Multiple sclerosis
120226     DB01273   Varenicline             C0026769  Multiple sclerosis

In [18]:
# Side effects of cocaine
se_df.query("drugbank_id == 'DB00953'")

      drugbank_id drugbank_name umls_cui_from_meddra         side_effect_name
84564     DB00953   Rizatriptan             C0232487     Abdominal discomfort
84445     DB00953   Rizatriptan             C0000731     Abdominal distension
84611     DB00953   Rizatriptan             C0000737           Abdominal pain
84507     DB00953   Rizatriptan             C0948089  Acute coronary syndrome
84548     DB00953   Rizatriptan             C0085631                Agitation
...           ...           ...                  ...                      ...
84540     DB00953   Rizatriptan             C0042571                  Vertigo
84582     DB00953   Rizatriptan             C0344232           Vision blurred
84541     DB00953   Rizatriptan             C0042963                 Vomiting
84542     DB00953   Rizatriptan             C0043144                 Wheezing
84544     DB00953   Rizatriptan             C0043387                  Yawning

[174 rows x 4 columns]

In [19]:
# Number of drugbank drugs
se_df.drugbank_id.nunique()

1223

In [20]:
# Number of UMLS side effects
se_df.umls_cui_from_meddra.nunique()

5734

In [21]:
# Save side effects
# se_df.to_csv('data/side-effects.tsv', sep='\t', index=False)

## meddra_all_indications.tsv.gz

In [60]:
columns = [
    'stitch_id_flat',
    'umls_cui_from_label',
    'method',
    'concept_name',
    'meddra_type',
    'umls_cui_from_meddra',
    'meddra_name',
]
indication_df = pandas.read_table('download/meddra_all_indications.tsv.gz', names=columns)
indication_df['pubchem_id'] = indication_df.stitch_id_flat.map(stitch_flat_to_pubchem)

In [65]:
indication_df

,stitch_id_flat,umls_cui_from_label,method,concept_name,meddra_type,umls_cui_from_meddra,meddra_name,pubchem_id
0,CID100000085,C0015544,text_mention,Failure to Thrive,LLT,C0015544,Failure to thrive,85.0
1,CID100000085,C0015544,text_mention,Failure to Thrive,PT,C0015544,Failure to thrive,85.0
2,CID100000085,C0020615,text_mention,Hypoglycemia,LLT,C0020615,Hypoglycaemia,85.0
3,CID100000085,C0020615,text_mention,Hypoglycemia,PT,C0020615,Hypoglycaemia,85.0
4,CID100000085,C0022661,NLP_indication,"Kidney Failure, Chronic",LLT,C0022661,Renal failure chronic,85.0
...,...,...,...,...,...,...,...,...
30830,CID171306834,C0524910,NLP_precondition,"Hepatitis C, Chronic",PT,C0524910,Chronic hepatitis C,71306834.0
30831,CID171306834,C0741132,text_mention,Antibody test positive,LLT,C0741132,Antibody test positive,71306834.0
30832,CID171306834,C0741132,text_mention,Antibody test positive,PT,C0741132,Antibody test positive,71306834.0
30833,CID171306834,C0856536,text_mention,Philadelphia chromosome positive,LLT,C0856536,Philadelphia chromosome positive,71306834.0
30834,CID171306834,C0856536,text_mention,Philadelphia chromosome positive,PT,C0476431,Chromosome analysis abnormal,71306834.0

In [74]:
indication_df['ChEMBL_ID'] = indication_df.apply(pubchem_id_to_InChIKey_to_ChEMBL_ID, axis=1)
indication_df

SSLError: HTTPSConnectionPool(host='www.ebi.ac.uk', port=443): Max retries exceeded with url: /unichem/rest/inchikey/UHDGCWIWMRVCDJ-UHFFFAOYSA-N (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1000)')))

#### This is a method to get drug name given stitich ID. However, we are not using it since the database is not complete, and we can get not only the drug name but also chembl ID from UniChem database directly

In [98]:
import requests
import json
def stitch_id_to_drug_name(row):
    stitch_id = row['stitch_id_flat']
    # Set the base URL and parameters
    base_url = "http://stitch.embl.de/api/json/resolve"
    params = {
        "identifier": stitch_id #"CID054684141",  # Replace "ADD" with your desired identifier
        #"species": 9606       # Species code for humans
    }
    
    # Make the GET request
    response = requests.get(base_url, params=params)
    
    # Check if the request was successful
    if response.status_code == 200:
        # Print the response content (which will be in TSV format)
        print(response.text)
        return json.loads(response.text)[0]['preferredName']

    return stitch_id

In [59]:
stitch_id = "CID100057469"

base_url = "http://stitch.embl.de/api/json/resolve"
params = {
    "identifier": stitch_id #"CID054684141",  # Replace "ADD" with your desired identifier
    #"species": 9606       # Species code for humans
}

# Make the GET request
response = requests.get(base_url, params=params)

# Check if the request was successful
if response.status_code == 200:
    # Print the response content (which will be in TSV format)
    print(response.text)
    # return json.loads(response.text)[0]['preferredName']

[{"ncbiTaxonId":-1,"stringId":"-1.CID100057469","queryIndex":0,"annotation":"imiquimod","preferredName":"imiquimod","taxonName":"small molecule"}]

In [69]:
import requests

# Set the base URL and parameters
base_url = "http://string-db.org/api/tsv/resolve"
params = {
    "identifier": "4-aminopyridin",  # Replace "ADD" with your desired identifier
    #"species": 9606       # Species code for humans
}

# Make the GET request
response = requests.get(base_url, params=params)

# Check if the request was successful
if response.status_code == 200:
    # Print the response content (which will be in TSV format)
    print(response.text)

stringId	ncbiTaxonId	taxonName	preferredName	annotation
10116.ENSRNOP00000040830	10116	Rattus norvegicus	Kcnq2	Potassium voltage-gated channel subfamily KQT member 2; Associates with KCNQ3 to form a potassium channel with essentially identical properties to the channel underlying the native M-current, a slowly activating and deactivating potassium conductance which plays a critical role in determining the subthreshold electrical excitability of neurons as well as the responsiveness to synaptic inputs. Therefore, it is important in the regulation of neuronal excitability. KCNQ2 current is blocked by barium and tetraethylammonium whereas 4-aminopyridine and charybdotoxin have no effect on KCNQ2 c [...]

In [55]:
response[0]

TypeError: 'Response' object is not subscriptable

In [57]:
import pandas as pd
import json

data = json.loads(response.text)
data[0]['preferredName']

'4-aminopyridine'

In [46]:
import requests

def get_drug_info_from_stitch(stitch_id):
    url = f"http://stitch.embl.de/api/json/abstracts/resolve?identifiers={stitch_id}"
    url = f"http://string-db.org/api/tsv/resolve?identifier=ADD&species=9606"
    
    response = requests.get(url)
    print(response)
    if response.status_code == 200:
        aliases = response.json()
        drug_info = {
            "drug_name": None,
            "drugbank_id": None
        }
        
        for alias in aliases:
            if 'DB' in alias['alias']:
                drug_info['drugbank_id'] = alias['alias']
            if 'PubChem Compound' in alias['source'] and drug_info['drug_name'] is None:
                drug_info['drug_name'] = alias['alias']
        
        return drug_info
    else:
        print(f"Error: Unable to retrieve data for STITCH ID {stitch_id}")
        return None

# Example usage
stitch_id = 'CID100001727'
drug_info = get_drug_info_from_stitch(stitch_id)
print(drug_info)

<Response [200]>

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [33]:
multiple_sclerosis_df = indication_df[indication_df['meddra_name'] == 'Multiple sclerosis'].query("meddra_type == 'PT'")
multiple_sclerosis_df

,stitch_id_flat,umls_cui_from_label,method,concept_name,meddra_type,umls_cui_from_meddra,meddra_name,pubchem_id
1915,CID100001727,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,1727.0
2058,CID100001875,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,1875.0
3639,CID100002284,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,2284.0
4722,CID100002554,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,2554.0
6970,CID100002891,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,2891.0
7220,CID100002951,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,2951.0
7500,CID100003003,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,3003.0
11264,CID100003640,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,3640.0
14088,CID100004159,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,4159.0
14766,CID100004212,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,4212.0
17251,CID100004894,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,4894.0
17463,CID100004895,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,4895.0
17637,CID100004896,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,4896.0
17851,CID100004900,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,4900.0
20333,CID100005487,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,5487.0
20843,CID100005544,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,5544.0
21582,CID100005877,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,5877.0
21872,CID100006436,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,6436.0
25273,CID100065370,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,65370.0
25950,CID100107969,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,107969.0
27850,CID103081884,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,3081884.0
27968,CID104479097,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,4479097.0
28589,CID106453361,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,6453361.0
29337,CID116129617,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,16129617.0
29568,CID116132265,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,16132265.0
30562,CID154677977,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,54677977.0

In [82]:
multiple_sclerosis_df.merge(drugbank_map_df_2, left_on = 'pubchem_id', right_on='pubchem_cid')

,stitch_id_flat,umls_cui_from_label,method,concept_name,meddra_type,umls_cui_from_meddra,meddra_name,pubchem_id,drugbankId,name,...,pubchem_cid,cas_num,chembl_id,zinc_id,chebi_id,kegg_cid,kegg_id,bindingDB_id,UMLS_cuis,stitch_id
0,CID100001727,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,1727.0,DB06637,Dalfampridine,...,1727.0,504-24-5,CHEMBL284348,ZINC000000599985,34385,C13728,D04127,10458.0,"C0000477,C0878240,C1449659",CID000001727
1,CID100002284,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,2284.0,DB00181,Baclofen,...,2284.0,1134-47-0,CHEMBL701,NaN,2972,NaN,D00241,24182.0,"C0004609,C4256145",CID000002284
2,CID100002554,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,2554.0,DB14498,Potassium acetate,...,2554.0,127-08-2,CHEMBL1201058,NaN,32029,C12554,NaN,NaN,C0137984,NaN
3,CID100002554,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,2554.0,DB00564,Carbamazepine,...,2554.0,298-46-4,CHEMBL108,ZINC000000004785,3387,C06868,D00252,50003659.0,C0006949,CID000002554
4,CID100004212,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,4212.0,DB01204,Mitoxantrone,...,4212.0,65271-80-9,CHEMBL58,ZINC000003794794,50729,C11195,D08224,67690.0,C0026259,CID000004212
5,CID100005487,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,5487.0,DB00697,Tizanidine,...,5487.0,51322-75-9,CHEMBL1079,ZINC000019702309,63629,C07452,D08611,50240671.0,C0146011,CID000005487

In [34]:
multiple_sclerosis_df.merge(drugbank_map_df_2, left_on="pubchem_id", right_on="pubchem_cid")

,stitch_id_flat,umls_cui_from_label,method,concept_name,meddra_type,umls_cui_from_meddra,meddra_name,pubchem_id,drugbankId,name,...,pubchem_cid,cas_num,chembl_id,zinc_id,chebi_id,kegg_cid,kegg_id,bindingDB_id,UMLS_cuis,stitch_id
0,CID100001727,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,1727.0,DB06637,Dalfampridine,...,1727.0,504-24-5,CHEMBL284348,ZINC000000599985,34385,C13728,D04127,10458.0,"C0000477,C0878240,C1449659",CID000001727
1,CID100002284,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,2284.0,DB00181,Baclofen,...,2284.0,1134-47-0,CHEMBL701,NaN,2972,NaN,D00241,24182.0,"C0004609,C4256145",CID000002284
2,CID100002554,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,2554.0,DB14498,Potassium acetate,...,2554.0,127-08-2,CHEMBL1201058,NaN,32029,C12554,NaN,NaN,C0137984,NaN
3,CID100002554,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,2554.0,DB00564,Carbamazepine,...,2554.0,298-46-4,CHEMBL108,ZINC000000004785,3387,C06868,D00252,50003659.0,C0006949,CID000002554
4,CID100004212,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,4212.0,DB01204,Mitoxantrone,...,4212.0,65271-80-9,CHEMBL58,ZINC000003794794,50729,C11195,D08224,67690.0,C0026259,CID000004212
5,CID100005487,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,5487.0,DB00697,Tizanidine,...,5487.0,51322-75-9,CHEMBL1079,ZINC000019702309,63629,C07452,D08611,50240671.0,C0146011,CID000005487

In [19]:
mapped_indication_df = indication_df.merge(drugbank_map_df_2, left_on='stitch_id_flat', right_on='stitch_id')
mapped_indication_df

,stitch_id_flat,umls_cui_from_label,method,concept_name,meddra_type,umls_cui_from_meddra,meddra_name,pubchem_id,drugbankId,name,...,pubchem_cid,cas_num,chembl_id,zinc_id,chebi_id,kegg_cid,kegg_id,bindingDB_id,UMLS_cuis,stitch_id
0,CID100000175,C0009450,text_mention,Communicable Diseases,LLT,C0009450,Infection,175.0,DB14511,Acetate,...,NaN,71-50-1,NaN,NaN,30089,NaN,NaN,50159793.0,NaN,CID100000175
1,CID100000175,C0009450,text_mention,Communicable Diseases,PT,C0009450,Infection,175.0,DB14511,Acetate,...,NaN,71-50-1,NaN,NaN,30089,NaN,NaN,50159793.0,NaN,CID100000175
2,CID100000175,C0020625,NLP_indication,Hyponatremia,LLT,C0020625,Hyponatraemia,175.0,DB14511,Acetate,...,NaN,71-50-1,NaN,NaN,30089,NaN,NaN,50159793.0,NaN,CID100000175
3,CID100000175,C0020625,NLP_indication,Hyponatremia,PT,C0020625,Hyponatraemia,175.0,DB14511,Acetate,...,NaN,71-50-1,NaN,NaN,30089,NaN,NaN,50159793.0,NaN,CID100000175
4,CID100000222,C0220983,text_mention,Metabolic alkalosis,LLT,C0220983,Metabolic alkalosis,222.0,DB11118,Ammonia,...,NaN,7664-41-7,NaN,NaN,NaN,NaN,NaN,NaN,C0002607,CID100000222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5175,CID154687131,C0040592,text_mention,Trachoma,PT,C0040592,Trachoma,54687131.0,DB00256,Lymecycline,...,54707177.0,992-21-2,CHEMBL2103929,ZINC000053682936,59040,NaN,D06884,NaN,C0024200,CID154687131
5176,CID154687131,C0149778,text_mention,Soft Tissue Infections,LLT,C0149778,Soft tissue infection,54687131.0,DB00256,Lymecycline,...,54707177.0,992-21-2,CHEMBL2103929,ZINC000053682936,59040,NaN,D06884,NaN,C0024200,CID154687131
5177,CID154687131,C0149778,text_mention,Soft Tissue Infections,PT,C0149778,Soft tissue infection,54687131.0,DB00256,Lymecycline,...,54707177.0,992-21-2,CHEMBL2103929,ZINC000053682936,59040,NaN,D06884,NaN,C0024200,CID154687131
5178,CID154687131,C1112709,text_mention,non-gonococcal urethritis (NGU),LLT,C1112709,Unspecified non-gonococcal urethritis (NGU),54687131.0,DB00256,Lymecycline,...,54707177.0,992-21-2,CHEMBL2103929,ZINC000053682936,59040,NaN,D06884,NaN,C0024200,CID154687131
5179,CID154687131,C1112709,text_mention,non-gonococcal urethritis (NGU),PT,C0041976,Urethritis,54687131.0,DB00256,Lymecycline,...,54707177.0,992-21-2,CHEMBL2103929,ZINC000053682936,59040,NaN,D06884,NaN,C0024200,CID154687131

In [21]:
mapped_indication_df[mapped_indication_df['meddra_name'] == 'Multiple sclerosis']

,stitch_id_flat,umls_cui_from_label,method,concept_name,meddra_type,umls_cui_from_meddra,meddra_name,pubchem_id,drugbankId,name,...,pubchem_cid,cas_num,chembl_id,zinc_id,chebi_id,kegg_cid,kegg_id,bindingDB_id,UMLS_cuis,stitch_id
958,CID100002891,C0026769,text_mention,Multiple Sclerosis,LLT,C0026769,Multiple sclerosis,2891.0,DB00115,Cyanocobalamin,...,70678590.0,68-19-9,CHEMBL2110563,NaN,17439,C02823,D00166,NaN,C0042845,CID100002891
959,CID100002891,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,2891.0,DB00115,Cyanocobalamin,...,70678590.0,68-19-9,CHEMBL2110563,NaN,17439,C02823,D00166,NaN,C0042845,CID100002891
996,CID100002951,C0026769,text_mention,Multiple Sclerosis,LLT,C0026769,Multiple sclerosis,2951.0,DB01219,Dantrolene,...,6914273.0,7261-97-4,CHEMBL1201288,ZINC000002568036,4317,C06939,D02347,50198767.0,C0010976,CID100002951
997,CID100002951,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,2951.0,DB01219,Dantrolene,...,6914273.0,7261-97-4,CHEMBL1201288,ZINC000002568036,4317,C06939,D02347,50198767.0,C0010976,CID100002951
4221,CID104479097,C0026769,text_mention,Multiple Sclerosis,LLT,C0026769,Multiple sclerosis,4479097.0,DB00200,Hydroxocobalamin,...,70678542.0,13422-51-0,CHEMBL2103737,NaN,27786,C08230,D01027,NaN,"C0003663,C0020316,C4256142",CID104479097
4222,CID104479097,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis,4479097.0,DB00200,Hydroxocobalamin,...,70678542.0,13422-51-0,CHEMBL2103737,NaN,27786,C08230,D01027,NaN,"C0003663,C0020316,C4256142",CID104479097

In [9]:
filtered_pubchem = drugbank_map_df[drugbank_map_df['drugbank_id'] == 'DB00115']

In [10]:
filtered_pubchem.merge(indication_df)

Empty DataFrame
Columns: [drugbank_id, pubchem_id, stitch_id_flat, umls_cui_from_label, method, concept_name, meddra_type, umls_cui_from_meddra, meddra_name]
Index: []

In [11]:
indication_df[indication_df['pubchem_id'] == int(17439)]

Empty DataFrame
Columns: [stitch_id_flat, umls_cui_from_label, method, concept_name, meddra_type, umls_cui_from_meddra, meddra_name, pubchem_id]
Index: []

In [30]:
drugbank_df[drugbank_df['drugbank_name'] == 'Cyanocobalamin']

    drugbank_id   drugbank_name
109     DB00115  Cyanocobalamin

In [44]:
drugbank_df

     drugbank_id        drugbank_name
0        DB00001            Lepirudin
1        DB00002            Cetuximab
2        DB00003         Dornase alfa
3        DB00004  Denileukin diftitox
4        DB00005           Etanercept
...          ...                  ...
7754     DB09023          Benactyzine
7755     DB09024    Follitropin Alpha
7756     DB09026            Aliskiren
7757     DB09028             Cytisine
7758     DB09029          Secukinumab

[7759 rows x 2 columns]

In [45]:
drugbank_map_df

       drugbank_id  pubchem_id
0          DB00014    11980055
1          DB00014    11981235
2          DB00014    11982741
3          DB00014    16052011
4          DB00014    23581804
...            ...         ...
204704     DB09028    74070157
204705     DB09028    74834862
204706     DB09028    77513518
204707     DB09028    87355970
204708     DB09028    87644641

[204709 rows x 2 columns]

In [41]:
indication_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30835 entries, 0 to 30834
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   stitch_id_flat        30835 non-null  object
 1   umls_cui_from_label   30835 non-null  object
 2   method                30835 non-null  object
 3   concept_name          30835 non-null  object
 4   meddra_type           30794 non-null  object
 5   umls_cui_from_meddra  30794 non-null  object
 6   meddra_name           30835 non-null  object
 7   pubchem_id            30835 non-null  float64
dtypes: float64(1), object(7)
memory usage: 1.9+ MB

In [23]:
indication_df = drugbank_df.merge(drugbank_map_df.merge(indication_df))
indication_df = indication_df.query("meddra_type == 'PT'")
indication_df.head(2)

,drugbank_id,drugbank_name,pubchem_id,stitch_id_flat,umls_cui_from_label,method,concept_name,meddra_type,umls_cui_from_meddra,meddra_name
1,DB00014,Goserelin,47725,CID100047725,C0002871,text_mention,Anemia,PT,C0002871,Anaemia
3,DB00014,Goserelin,47725,CID100047725,C0006142,NLP_indication,Malignant neoplasm of breast,PT,C0006142,Breast cancer

In [24]:
indication_df[indication_df['drugbank_id'] == 'DB00115']

Empty DataFrame
Columns: [drugbank_id, drugbank_name, pubchem_id, stitch_id_flat, umls_cui_from_label, method, concept_name, meddra_type, umls_cui_from_meddra, meddra_name]
Index: []

In [25]:
indication_df[indication_df['meddra_name'] == 'Multiple sclerosis']

,drugbank_id,drugbank_name,pubchem_id,stitch_id_flat,umls_cui_from_label,method,concept_name,meddra_type,umls_cui_from_meddra,meddra_name
604,DB00181,Baclofen,2284,CID100002284,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
6385,DB00443,Betamethasone,3003,CID100003003,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
9221,DB00564,Carbamazepine,2554,CID100002554,C0026769,NLP_indication,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
10580,DB00620,Triamcinolone,5544,CID100005544,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
11048,DB00635,Prednisone,4900,CID100004900,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
12222,DB00697,Tizanidine,5487,CID100005487,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
13226,DB00741,Hydrocortisone,3640,CID100003640,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
15500,DB00860,Prednisolone,4894,CID100004894,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
17142,DB00959,Methylprednisolone,4159,CID100004159,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
22470,DB01204,Mitoxantrone,4212,CID100004212,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
22690,DB01219,Dantrolene,2951,CID100002951,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
23159,DB01234,Dexamethasone,3003,CID100003003,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
27776,DB05286,FTY 720,107969,CID100107969,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
29109,DB06637,Dalfampridine,1727,CID100001727,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
30106,DB07886,"(11alpha,14beta)-11,17,21-trihydroxypregn-4-en...",3640,CID100003640,C0026769,text_mention,Multiple Sclerosis,PT,C0026769,Multiple sclerosis
30975,DB08868,Fingolimod,107969,CID100107969,C0026769,NLP_precondition,Multiple Sclerosis,PT,C0026769,Multiple sclerosis

In [77]:
indication_df[indication_df['meddra_name'] == 'Multiple sclerosis'].drugbank_name.tolist()

['Baclofen',
 'Betamethasone',
 'Carbamazepine',
 'Triamcinolone',
 'Prednisone',
 'Tizanidine',
 'Hydrocortisone',
 'Prednisolone',
 'Methylprednisolone',
 'Mitoxantrone',
 'Dantrolene',
 'Dexamethasone',
 'FTY 720',
 'Dalfampridine',
 '(11alpha,14beta)-11,17,21-trihydroxypregn-4-ene-3,20-dione',
 'Fingolimod']

### Question left to resolve: some drugs don't appear as indication even though they appear on the webpage: cyanocobalamin for side effect Multiple sclerosis

In [48]:
indication_df[indication_df['drugbank_name'].str.contains('Cevimeline')]

,drugbank_id,drugbank_name,pubchem_id,stitch_id_flat,umls_cui_from_label,method,concept_name,meddra_type,umls_cui_from_meddra,meddra_name
712,DB00185,Cevimeline,2684,CID100002684,C0043352,NLP_indication,Xerostomia,PT,C0043352,Dry mouth
714,DB00185,Cevimeline,2684,CID100002684,C1527336,NLP_indication,Sjogren's Syndrome,PT,C1527336,Sjogren's syndrome

In [17]:
# Multiple Sclerosis indications
indication_df.query("umls_cui_from_meddra == 'C0026769'").drugbank_name.tolist()

['Baclofen',
 'Betamethasone',
 'Carbamazepine',
 'Triamcinolone',
 'Prednisone',
 'Tizanidine',
 'Hydrocortisone',
 'Prednisolone',
 'Methylprednisolone',
 'Mitoxantrone',
 'Dantrolene',
 'Dexamethasone',
 'FTY 720',
 'Dalfampridine',
 '(11alpha,14beta)-11,17,21-trihydroxypregn-4-ene-3,20-dione',
 'Fingolimod']

In [22]:
# Save indications
# indication_df.to_csv('data/indications.tsv', sep='\t', index=False)

In [23]:
import pandas as pd
import numpy as np
from chembl_webresource_client.new_client import new_client
import datetime
import ast

In [24]:
from chembl_webresource_client.new_client import new_client

# Define a function to retrieve DrugBank IDs based on ChEMBL IDs
def get_drugbank_id(chembl_id):
    # Create a new ChEMBL client
    chembl = new_client

    # Search for the molecule based on ChEMBL ID
    molecule = chembl.molecule.filter(chembl_id=chembl_id) #.only(['drugbank_id'])

    # Extract DrugBank ID if available
    print(molecule)
    drugbank_id = molecule[0]['drugbank_id'] if molecule else None

    return drugbank_id

# Example usage
chembl_id = 'CHEMBL3039597'  # Replace this with your ChEMBL ID
drugbank_id = get_drugbank_id(chembl_id)
if drugbank_id:
    print(f"The DrugBank ID for ChEMBL ID {chembl_id} is: {drugbank_id}")
else:
    print(f"No DrugBank ID found for ChEMBL ID {chembl_id}")

[{'atc_classifications': ['S01AA11', 'S02AA14', 'J01GB03', 'S03AA06', 'D06AX07'], 'availability_type': 1, 'biotherapeutic': None, 'black_box_warning': 1, 'chebi_par_id': None, 'chemical_probe': 0, 'chirality': -1, 'cross_references': [{'xref_id': '4265', 'xref_name': 'gentamicin', 'xref_src': 'DrugCentral'}], 'dosed_ingredient': False, 'first_approval': 1970, 'first_in_class': 0, 'helm_notation': None, 'indication_class': 'Antibacterial', 'inorganic_flag': 0, 'max_phase': '4.0', 'molecule_chembl_id': 'CHEMBL3039597', 'molecule_hierarchy': {'active_chembl_id': 'CHEMBL3039597', 'molecule_chembl_id': 'CHEMBL3039597', 'parent_chembl_id': 'CHEMBL3039597'}, 'molecule_properties': {'alogp': None, 'aromatic_rings': None, 'cx_logd': None, 'cx_logp': None, 'cx_most_apka': None, 'cx_most_bpka': None, 'full_molformula': 'C60H123N15O21', 'full_mwt': '1390.73', 'hba': None, 'hba_lipinski': None, 'hbd': None, 'hbd_lipinski': None, 'heavy_atoms': None, 'molecular_species': None, 'mw_freebase': '1390.73', 'mw_monoisotopic': '1389.9018', 'np_likeness_score': None, 'num_lipinski_ro5_violations': None, 'num_ro5_violations': None, 'psa': None, 'qed_weighted': None, 'ro3_pass': None, 'rtb': None}, 'molecule_structures': {'canonical_smiles': 'CNC(C)[C@@H]1CC[C@@H](N)[C@@H](O[C@H]2[C@H](O)[C@@H](O[C@H]3OC[C@](C)(O)[C@H](NC)[C@H]3O)[C@H](N)C[C@@H]2N)O1.CN[C@@H]1[C@@H](O)[C@@H](O[C@@H]2[C@@H](O)[C@H](O[C@H]3O[C@H](C(C)N)CC[C@H]3N)[C@@H](N)C[C@H]2N)OC[C@]1(C)O.CN[C@@H]1[C@@H](O)[C@@H](O[C@@H]2[C@@H](O)[C@H](O[C@H]3O[C@H](CN)CC[C@H]3N)[C@@H](N)C[C@H]2N)OC[C@]1(C)O', 'molfile': '\n     RDKit          2D\n\n105111  0  0  0  0  0  0  0  0999 V2000\n    6.6418   -8.0218    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.4029   -7.3076    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.8208   -8.0218    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.4594   -8.4445    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.8676   -7.7303    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.6334   -8.4445    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.5818   -7.3076    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    7.3561   -8.4299    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    7.7642   -9.1442    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.2107   -7.7303    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    7.0598   -7.3076    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.8208   -6.5933    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    8.5950   -9.1442    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    3.4594   -7.0160    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    6.6418   -6.5933    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.6334   -7.0160    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    7.3561   -9.8584    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.2205   -9.1587    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    3.8724   -9.1587    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    5.4029   -8.7360    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    7.7642  -10.5726    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    7.8808   -7.3076    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    5.4029   -5.8791    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    9.0032   -9.8584    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.4964   -7.3172    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    6.5252   -9.8584    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    8.5950  -10.5726    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   10.4316   -9.8438    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    1.4964   -8.1384    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    9.7126   -9.4357    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.3944   -9.1587    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.5818   -8.1384    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    9.7174  -10.2762    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    6.6418   -8.8477    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.8697   -2.9056    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.3693   -2.1913    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0388   -2.9056    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.3225   -3.3283    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.9144   -2.6140    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.1436   -3.3283    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.9920   -4.0376    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.2001   -2.2010    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    1.5839   -3.3234    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    2.8181   -4.0376    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.5615   -2.6140    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.2778   -2.1913    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0388   -1.4771    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.3225   -1.8998    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    0.8697   -1.4771    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.2310   -4.7518    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.1436   -1.8998    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.5791   -4.7518    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.5615   -4.0425    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    2.8181   -5.4661    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.9920   -5.4661    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.9046   -4.0425    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.3693   -3.6198    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.3693   -0.7629    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    2.1086   -2.2010    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    3.9405   -4.3340    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -4.2903   -2.2059    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    3.9307   -3.5032    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    0.7531   -4.7518    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n   -4.2903   -3.0222    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -4.3825   -4.0425    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.6449   -3.0805    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.6595   -4.7373    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.8649   -3.7364    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.2001   -3.0318    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    3.9405   -5.1649    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n   12.4238   -2.9056    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   11.1848   -2.1913    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   11.5977   -2.9056    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    9.2364   -3.3283    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    9.6445   -2.6140    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    8.4055   -3.3283    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   13.5462   -4.0376    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   10.3588   -2.2010    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   13.1380   -3.3234    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   14.3672   -4.0376    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    7.9926   -2.6140    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   12.8367   -2.1913    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   11.5977   -1.4771    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    9.2364   -1.8998    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   12.4238   -1.4771    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   14.7851   -4.7518    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    8.4055   -1.8998    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   13.1282   -4.7518    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    7.9974   -4.0425    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n   14.3672   -5.4661    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   13.5462   -5.4661    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    9.6445   -4.0425    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   11.1848   -3.6198    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   11.1848   -0.7629    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n   13.6628   -2.2010    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n   15.4896   -4.3340    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    7.2686   -2.2059    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   12.3023   -4.7518    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n   15.4896   -3.5032    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    7.2686   -3.0222    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    7.1666   -4.0425    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   16.2136   -4.7373    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   10.3588   -3.0318    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n   12.4140   -3.7364    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n   15.4896   -5.1649    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n  2  3  1  0\n  3  1  1  0\n  4  5  1  0\n  5  7  1  0\n  6  4  1  0\n  2  7  1  1\n  8  1  1  0\n  9  8  1  1\n 10 16  1  0\n 11  1  1  0\n 12 15  1  0\n 13  9  1  0\n 14  5  1  0\n 15 11  1  0\n 16 14  1  0\n 17  9  1  0\n  6 18  1  1\n  4 19  1  6\n  3 20  1  6\n 21 17  1  0\n 11 22  1  6\n 12 23  1  6\n 24 13  1  0\n 10 25  1  1\n 17 26  1  1\n 27 21  1  0\n 28 30  1  0\n 29 10  1  0\n 30 24  1  0\n 31 18  1  0\n  5 32  1  1\n 24 33  1  1\n  1 34  1  6\n 12  2  1  0\n 27 24  1  0\n  6 10  1  0\n 45 61  1  1\n 52 63  1  1\n 64 45  1  0\n 65 53  1  0\n 66 62  1  0\n 67 60  1  0\n 35 68  1  6\n 39 69  1  1\n 50 70  1  1\n 36 47  1  0\n 55 54  1  0\n 40 45  1  0\n 36 37  1  0\n 37 35  1  0\n 38 39  1  0\n 39 42  1  0\n 40 38  1  0\n 41 43  1  1\n 36 42  1  1\n 43 35  1  0\n 44 41  1  0\n 45 51  1  0\n 46 35  1  0\n 47 49  1  0\n 48 39  1  0\n 49 46  1  0\n 50 44  1  0\n 51 48  1  0\n 52 41  1  0\n 40 53  1  1\n 54 50  1  0\n 55 52  1  0\n 38 56  1  6\n 37 57  1  6\n 47 58  1  6\n 46 59  1  6\n 60 50  1  0\n 60 62  1  0\n 72 73  1  0\n 73 71  1  0\n 74 75  1  0\n 75 78  1  0\n 76 74  1  0\n 77 79  1  1\n 72 78  1  1\n 79 71  1  0\n 80 77  1  0\n 81 87  1  0\n 82 71  1  0\n 83 85  1  0\n 84 75  1  0\n 85 82  1  0\n 86 80  1  0\n 87 84  1  0\n 88 77  1  0\n 76 89  1  1\n 90 91  1  0\n 91 88  1  0\n 74 92  1  6\n 73 93  1  6\n 83 94  1  6\n 82 95  1  6\n 96 86  1  0\n 81 97  1  1\n 88 98  1  1\n100 81  1  0\n101 89  1  0\n102 96  1  0\n 75103  1  1\n 71104  1  6\n 86105  1  1\n 83 72  1  0\n 90 86  1  0\n 76 81  1  0\n 96 99  1  0\nM  END\n> <chembl_id>\nCHEMBL3039597\n\n> <chembl_pref_name>\nGENTAMICIN', 'standard_inchi': 'InChI=1S/C21H43N5O7.C20H41N5O7.C19H39N5O7/c1-9(25-3)13-6-5-10(22)19(31-13)32-16-11(23)7-12(24)17(14(16)27)33-20-15(28)18(26-4)21(2,29)8-30-20;1-8(21)12-5-4-9(22)18(30-12)31-15-10(23)6-11(24)16(13(15)26)32-19-14(27)17(25-3)20(2,28)7-29-19;1-19(27)7-28-18(13(26)16(19)24-2)31-15-11(23)5-10(22)14(12(15)25)30-17-9(21)4-3-8(6-20)29-17/h9-20,25-29H,5-8,22-24H2,1-4H3;8-19,25-28H,4-7,21-24H2,1-3H3;8-18,24-27H,3-7,20-23H2,1-2H3/t9?,10-,11+,12-,13+,14+,15-,16-,17+,18-,19-,20-,21+;8?,9-,10+,11-,12+,13+,14-,15-,16+,17-,18-,19-,20+;8-,9+,10-,11+,12-,13+,14+,15-,16+,17+,18+,19-/m110/s1', 'standard_inchi_key': 'NPEFREDMMVQEPL-RWPARATISA-N'}, 'molecule_synonyms': [{'molecule_synonym': 'Gentamicin', 'syn_type': 'ATC', 'synonyms': 'GENTAMICIN'}, {'molecule_synonym': 'Gentamicin', 'syn_type': 'BAN', 'synonyms': 'GENTAMICIN'}, {'molecule_synonym': 'Gentamicin', 'syn_type': 'INN', 'synonyms': 'GENTAMICIN'}, {'molecule_synonym': 'Gentamicin', 'syn_type': 'MERCK_INDEX', 'synonyms': 'GENTAMICIN'}, {'molecule_synonym': 'Gentamicin', 'syn_type': 'OTHER', 'synonyms': 'GENTAMICIN'}, {'molecule_synonym': 'Gentamycin', 'syn_type': 'OTHER', 'synonyms': 'GENTAMYCIN'}, {'molecule_synonym': 'Lyramycin', 'syn_type': 'OTHER', 'synonyms': 'LYRAMYCIN'}, {'molecule_synonym': 'Oksitselanim', 'syn_type': 'OTHER', 'synonyms': 'OKSITSELANIM'}, {'molecule_synonym': 'SCH-9724', 'syn_type': 'RESEARCH_CODE', 'synonyms': 'SCH-9724'}, {'molecule_synonym': 'Septigen', 'syn_type': 'OTHER', 'synonyms': 'SEPTIGEN'}, {'molecule_synonym': 'Uromycine', 'syn_type': 'OTHER', 'synonyms': 'Uromycine'}], 'molecule_type': 'Small molecule', 'natural_product': 0, 'oral': False, 'orphan': 0, 'parenteral': True, 'polymer_flag': 0, 'pref_name': 'GENTAMICIN', 'prodrug': 0, 'structure_type': 'MOL', 'therapeutic_flag': True, 'topical': True, 'usan_stem': '-micin', 'usan_stem_definition': 'antibiotics (Micromonospora strains)', 'usan_substem': '-micin', 'usan_year': 1963, 'withdrawn_flag': False}]

KeyError: 'drugbank_id'

In [25]:
activities = new_client.activity

In [ ]:
chem_id = 'CHEMBL3039597'
res = activities.filter(molecule_chembl_id=chem_id)
target_list = []
for element in res:
    print(element)
    # if element['type'] == 'IC50':
    #     if element['standard_value']:
    #         if float(element['standard_value']) <= 1000:
    #             target_id = element['target_chembl_id']
    #             target_name = element['target_pref_name']
    #             target_list.append(target_id)
    #             if target_id not in target_id_name_dict.keys():
    #                 target_id_name_dict[target_id] = target_name
    #                 temp = pd.DataFrame([[target_id, target_name]],columns=['ChEBML ID', 'Name'])
    #                 target_id_name_df = pd.concat([target_id_name_df, temp])
# drug_dict[chem_id] = target_list

In [ ]:
molecule = new_client.molecule

In [21]:
mols = molecule.filter(

SyntaxError: incomplete input (52802753.py, line 1)

In [ ]:
mols = molecule.filter(molecule_chembl_id__icontains=chem_id)

# UniChem Cross References

In [1]:
import requests

def get_drugbank_id_from_chembl(chembl_id):
    # UniChem API endpoint for ChEMBL to DrugBank mappings
    api_url = "https://www.ebi.ac.uk/unichem/api/v1/connectivity"
    todo = {"compound": chembl_id, "searchComponents": False,  "sourceID": 1,  "type": 'sourceID'}

    try:
        # Make GET request to UniChem API
        response = requests.post(api_url, json=todo)
        response.raise_for_status()  # Raise an exception for HTTP errors

        # Parse JSON response
        data = response.json()
        # print(data)
        # Extract DrugBank ID from response
        drugbank_id = None
        # for mapping in data:
        #     if mapping['src_id'] == 22:  # DrugBank source ID
        #         drugbank_id = mapping['dest_compound_id']
        #         break
        if data['response'] == 'Not found':
            return None
        for element in data['sources']:
            if element['comparison']['stereoType'] == True and element['longName'] == 'DrugBank':
                drugbank_id = element['compoundId']

        return drugbank_id

    except requests.exceptions.RequestException as e:
        print("Error fetching data:", e)
        return None

# Example usage
chembl_id = "CHEMBL1622"
drugbank_id = get_drugbank_id_from_chembl(chembl_id)
if drugbank_id:
    print(f"The DrugBank ID corresponding to ChEMBL ID {chembl_id} is {drugbank_id}.")
else:
    print(f"No DrugBank ID found for ChEMBL ID {chembl_id}.")

The DrugBank ID corresponding to ChEMBL ID CHEMBL1622 is DB00158.

In [ ]:
import requests
api_url = "https://www.ebi.ac.uk/unichem/api/v1/connectivity"
todo = {"compound": "CHEMBL2108675", "searchComponents": False,  "sourceID": 1,  "type": 'sourceID'}
response = requests.post(api_url, json=todo)
data = response.json()
response.json()

In [ ]:
for element in data['sources']:
    if element['comparison']['stereoType'] == True and element['longName'] == 'DrugBank':
        print(element['compoundId'])

In [ ]:
import requests
api_url = "https://jsonplaceholder.typicode.com/todos"
todo = {"userId": 1, "title": "Buy milk", "completed": False}
response = requests.post(api_url, json=todo)
response.json()


response.status_code